# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ObjectDetectionService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ObjectDetectionService.proto',
  package='objectDetection_grpc',
  syntax='proto3',
  serialized_pb=_b('\n\x1cObjectDetectionService.proto\x12\x14objectDetection_grpc\"\x1b\n\nqueryImage\x12\r\n\x05image\x18\x01 \x01(\x0c\"J\n\x0erespondMessage\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\t\n\x01x\x18\x02 \x03(\x01\x12\t\n\x01y\x18\x03 \x03(\x01\x12\t\n\x01z\x18\x04 \x03(\x01\x12\t\n\x01w\x18\x05 \x03(\x01\x32v\n\x16ObjectDetectionService\x12\\\n\x0cobjectDetect\x12 .objectDetection_grpc.queryImage\x1a$.objectDetection_grpc.respondMessage\"\x00(\x01\x30\x01\x42\x34\n\x1c\x65\x64u.berkeley.cs.sdb.cellmateB\x14ObjectDetectionProtob\x06proto3')
)




_QUERYIMAGE = _descriptor.Descriptor(
  name='queryImage',
  full_name='objectDetection_grpc.queryImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='objectDetection_grpc.queryImage.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=81,
)


_RESPONDMESSAGE = _descriptor.Descriptor(
  name='respondMessage',
  full_name='objectDetection_grpc.respondMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='objectDetection_grpc.respondMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='objectDetection_grpc.respondMessage.x', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='objectDetection_grpc.respondMessage.y', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='objectDetection_grpc.respondMessage.z', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='objectDetection_grpc.respondMessage.w', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['queryImage'] = _QUERYIMAGE
DESCRIPTOR.message_types_by_name['respondMessage'] = _RESPONDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

queryImage = _reflection.GeneratedProtocolMessageType('queryImage', (_message.Message,), dict(
  DESCRIPTOR = _QUERYIMAGE,
  __module__ = 'ObjectDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection_grpc.queryImage)
  ))
_sym_db.RegisterMessage(queryImage)

respondMessage = _reflection.GeneratedProtocolMessageType('respondMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONDMESSAGE,
  __module__ = 'ObjectDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:objectDetection_grpc.respondMessage)
  ))
_sym_db.RegisterMessage(respondMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034edu.berkeley.cs.sdb.cellmateB\024ObjectDetectionProto'))

_OBJECTDETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ObjectDetectionService',
  full_name='objectDetection_grpc.ObjectDetectionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=159,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='objectDetect',
    full_name='objectDetection_grpc.ObjectDetectionService.objectDetect',
    index=0,
    containing_service=None,
    input_type=_QUERYIMAGE,
    output_type=_RESPONDMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTDETECTIONSERVICE)

DESCRIPTOR.services_by_name['ObjectDetectionService'] = _OBJECTDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
