# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ObjectDetectionService_pb2 as ObjectDetectionService__pb2


class ObjectDetectionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.objectDetect = channel.stream_stream(
        '/objectDetection_grpc.ObjectDetectionService/objectDetect',
        request_serializer=ObjectDetectionService__pb2.queryImage.SerializeToString,
        response_deserializer=ObjectDetectionService__pb2.respondMessage.FromString,
        )


class ObjectDetectionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def objectDetect(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ObjectDetectionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'objectDetect': grpc.stream_stream_rpc_method_handler(
          servicer.objectDetect,
          request_deserializer=ObjectDetectionService__pb2.queryImage.FromString,
          response_serializer=ObjectDetectionService__pb2.respondMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'objectDetection_grpc.ObjectDetectionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
